name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: melvinlarsson/myrepo:1.1
      credentials:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      volumes:
        - .:/src

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Build
        run: make
  test:
    runs-on: ubuntu-latest

    env:
      PREFIX: "${{ github.workspace }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Run Tests
        run: |
          ./tests/test_all.sh
          if [ $? -eq 0 ]; then
            echo "Tests passed!"
          else
            echo "Tests failed!" >&2
            exit 1
          fi
